set={1,2,3,4,"nagoorbe"}
set.add(5)
print(set)
set.remove(2)
print(set)
set.add(5)
print(set)
set2={3,8,4,"python"}
print(set.difference(set2))
print(set.difference_update(set2))
set.discard("nagoorbe")
print(set)
set.clear()
print(set)